In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("./data/online_retail_II.xlsx")

In [25]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [26]:
df.info()

<class 'pandas.DataFrame'>
Index: 417534 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      417534 non-null  object
 1   StockCode    417534 non-null  object
 2   Description  417534 non-null  object
 3   Quantity     417534 non-null  int64
 4   InvoiceDate  417534 non-null  datetime64[us]
 5   Price        417534 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      417534 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 28.7+ MB

In [27]:
df = df.dropna(subset=["Customer ID", "Description"])

In [28]:
type(df["Invoice"])

pandas.Series

In [29]:
df[~df['Invoice'].astype(str).str.startswith("C")]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
...,...,...,...,...,...,...,...,...
525456,538171,22271,FELTCRAFT DOLL ROSIE,2,2010-12-09 20:01:00,2.95,17530.0,United Kingdom
525457,538171,22750,FELTCRAFT PRINCESS LOLA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525458,538171,22751,FELTCRAFT PRINCESS OLIVIA DOLL,1,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525459,538171,20970,PINK FLORAL FELTCRAFT SHOULDER BAG,2,2010-12-09 20:01:00,3.75,17530.0,United Kingdom
525460,538171,21931,JUMBO STORAGE BAG SUKI,2,2010-12-09 20:01:00,1.95,17530.0,United Kingdom

In [30]:
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

In [31]:
SimpleDocTemplate("retail.pdf",
                  pagesize = A4,
                  rightMargin = 40,
                  leftMargin = 40,
                  toptMargin = 40,
                  bottomMargin = 40
                )

In [32]:
# Document setup
doc = SimpleDocTemplate("retail.pdf",
                  pagesize = A4,
                  rightMargin = 40,
                  leftMargin = 40,
                  toptMargin = 40,
                  bottomMargin = 40
                )

In [33]:
dict(getSampleStyleSheet())            # Preset reportlab styles

KeyError: "Style '0' not found in stylesheet"

In [ ]:
styles = getSampleStyleSheet()
print(styles.byName.keys())

dict_keys(['Normal', 'BodyText', 'Italic', 'Heading1', 'Title', 'Heading2', 'Heading3', 'Heading4', 'Heading5', 'Heading6', 'Bullet', 'Definition', 'Code', 'UnorderedList', 'OrderedList'])

In [ ]:
print(styles["BodyText"])

<ParagraphStyle 'BodyText'>

In [ ]:
print(styles["BodyText"].__dict__)

{'name': 'BodyText', 'parent': <ParagraphStyle 'Normal'>, 'fontName': 'Helvetica', 'fontSize': 10, 'leading': 12, 'leftIndent': 0, 'rightIndent': 0, 'firstLineIndent': 0, 'alignment': 0, 'spaceBefore': 6, 'spaceAfter': 0, 'bulletFontName': 'Helvetica', 'bulletFontSize': 10, 'bulletIndent': 0, 'textColor': Color(0,0,0,1), 'backColor': None, 'wordWrap': None, 'shaping': 0, 'borderWidth': 0, 'borderPadding': 0, 'borderColor': None, 'borderRadius': None, 'allowWidows': 1, 'allowOrphans': 0, 'textTransform': None, 'endDots': None, 'splitLongWords': 1, 'underlineWidth': '', 'bulletAnchor': 'start', 'justifyLastLine': 0, 'justifyBreaks': 0, 'spaceShrinkage': 0.05, 'strikeWidth': '', 'underlineOffset': '-0.125*F', 'underlineGap': '1', 'strikeOffset': '0.25*F', 'strikeGap': '1', 'linkUnderline': 0, 'underlineColor': None, 'strikeColor': None, 'hyphenationLang': '', 'embeddedHyphenation': 0, 'uriWasteReduce': 0}

In [55]:
story = []

In [ ]:
# Custom heading Style
heading_style = ParagraphStyle(
    "Heading1",
    parent=styles["Heading1"],
    fontSize=20,
    spaceAfter=12,
    alignment=1 # center 
)

In [57]:
# Title

story.append(Paragraph("Monthly Performance Report", heading_style))
story.append(Spacer(1,12))
story.append(Paragraph("Paragraph Text here",styles["BodyText"] ))

In [58]:
story

[Paragraph(
 'caseSensitive': 1
 'encoding': 'utf8'
 'text': 'Monthly Performance Report'
 'frags': [ParaFrag(__tag__='para', bold=1, fontName='Helvetica-Bold', fontSize=20, greek=0, italic=0, link=[], rise=0, text='Monthly Performance Report', textColor=Color(0,0,0,1), us_lines=[])]
 'style': <ParagraphStyle 'Heading1'>
 'bulletText': None
 'debug': 0
 ) #Paragraph,
 Spacer(1, 12),
 Paragraph(
 'caseSensitive': 1
 'encoding': 'utf8'
 'text': 'Paragraph Text here'
 'frags': [ParaFrag(__tag__='para', bold=0, fontName='Helvetica', fontSize=10, greek=0, italic=0, link=[], rise=0, text='Paragraph Text here', textColor=Color(0,0,0,1), us_lines=[])]
 'style': <ParagraphStyle 'BodyText'>
 'bulletText': None
 'debug': 0
 ) #Paragraph]

In [59]:
doc.build(story)

In [61]:
# Pandas Table Scrapping

df_scrap = pd.read_html(r"https://archive.ics.uci.edu/dataset/352/online+retail")

In [62]:
df_scrap

[  Variable Name     Role         Type  \
 0     InvoiceNo       ID  Categorical
 1     StockCode       ID  Categorical
 2   Description  Feature  Categorical
 3      Quantity  Feature      Integer
 4   InvoiceDate  Feature         Date
 5     UnitPrice  Feature   Continuous
 6    CustomerID  Feature  Categorical
 7       Country  Feature  Categorical

                                          Description     Units Missing Values
 0  a 6-digit integral number uniquely assigned to...       NaN             no
 1  a 5-digit integral number uniquely assigned to...       NaN             no
 2                                       product name       NaN             no
 3  the quantities of each product (item) per tran...       NaN             no
 4  the day and time when each transaction was gen...       NaN             no
 5                             product price per unit  sterling             no
 6  a 5-digit integral number uniquely assigned to...       NaN             no
 7  the name of the country where each customer re...       NaN             no  ,
                  File     Size
 0  Online Retail.xlsx  22.6 MB]

In [64]:
print(len(df_scrap))
print(type(df_scrap))

2
<class 'list'>

In [65]:
df_scrap[0]

,Variable Name,Role,Type,Description,Units,Missing Values
0,InvoiceNo,ID,Categorical,a 6-digit integral number uniquely assigned to...,NaN,no
1,StockCode,ID,Categorical,a 5-digit integral number uniquely assigned to...,NaN,no
2,Description,Feature,Categorical,product name,NaN,no
3,Quantity,Feature,Integer,the quantities of each product (item) per tran...,NaN,no
4,InvoiceDate,Feature,Date,the day and time when each transaction was gen...,NaN,no
5,UnitPrice,Feature,Continuous,product price per unit,sterling,no
6,CustomerID,Feature,Categorical,a 5-digit integral number uniquely assigned to...,NaN,no
7,Country,Feature,Categorical,the name of the country where each customer re...,NaN,no

In [66]:
df_scrap[1]

                 File     Size
0  Online Retail.xlsx  22.6 MB

In [69]:
# Webscrapping to get dataset description


import requests
from bs4 import BeautifulSoup

In [ ]:
url = r"https://archive.ics.uci.edu/dataset/352/online+retail"
response = requests.get(url)           # Downloadig the webpage

In [ ]:
response.text              # Raw html string

'<!DOCTYPE html>\n<html lang="en" data-theme="light">\n  <head>\n    <meta charset="UTF-8" />\n\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n\n    <meta name="description" content="Discover datasets around the world!" />\n\n    <link rel="icon" href="/favicon.ico" />\n\n    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />\n\n    <!-- Provides metadata used when the app is installed on a mobile device or desktop. -->\n    <!-- See https://developers.google.com/web/fundamentals/web-app-manifest/ -->\n    <link rel="manifest" href="/manifest.json" />\n\n    <title>UCI Machine Learning Repository</title>\n\n    \n\t\t<link href="../../_app/immutable/assets/0.ab4ca364.css" rel="stylesheet">\n\t\t<link href="../../_app/immutable/assets/Autocomplete.3d8e18c6.css" rel="stylesheet">\n\t\t<link href="../../_app/immutable/assets/DropdownText.035f3ed6.css" rel="stylesheet">\n\t\t<link href="../../_app/immutable/assets/JsonDiff.b38ce334.css" rel="stylesheet">\n\t\t<link href="../../_app/immutable/assets/Variables.ad52176b.css" rel="stylesheet"><title>Online Retail - UCI Machine Learning Repository</title><!-- HEAD_svelte-mjc4kk_START --><script async src="https://www.googletagmanager.com/gtag/js?id=G-MTKKEPF231"></script><!-- HTML_TAG_START -->\n    <script>\n      window.dataLayer = window.dataLayer ?? []\n      function gtag() {\n        dataLayer.push(arguments)\n      }\n      gtag(\'js\', new Date())\n      gtag(\'config\', "G-MTKKEPF231")\n    </script>\n  <!-- HTML_TAG_END --><!-- HEAD_svelte-mjc4kk_END --><!-- HEAD_svelte-q2bizo_START --><!-- HEAD_svelte-q2bizo_END -->\n  </head>\n  <body>\n    <div>     <div class="drawer h-full"> <input id="daisy-ui-drawer-checkbox" type="checkbox" class="drawer-toggle" aria-label="toggle drawer">  <div class="drawer-content"> <header class="navbar shadow-md"><div class="navbar-start gap-1"><label for="daisy-ui-drawer-checkbox" class="drawer-button btn btn-ghost lg:hidden"><svg viewBox="0 0 24 24" width="24" height="24" class="text-primary"><!-- HTML_TAG_START --><path fill="currentColor" d="M3 18v-2h18v2zm0-5v-2h18v2zm0-5V6h18v2z"/><!-- HTML_TAG_END --></svg></label> <a href="/" class="btn btn-ghost" aria-label="Home Page"><svg id="Layer_1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 235.04 62.85" class="h-10 fill-primary"><!-- HTML_TAG_START --><g\n    ><path\n      d="M102.76,2.35h2.57v7.43c0,.83,.1,1.44,.29,1.82,.31,.68,.97,1.02,1.99,1.02s1.68-.34,1.99-1.02c.2-.38,.29-.99,.29-1.82V2.35h2.57v7.43c0,1.29-.2,2.29-.6,3-.74,1.31-2.16,1.97-4.25,1.97s-3.51-.66-4.26-1.97c-.4-.72-.6-1.72-.6-3V2.35Z"\n    /><path\n      d="M116.05,3.62c.97-1,2.21-1.49,3.72-1.49,2.01,0,3.48,.67,4.42,2,.51,.75,.79,1.5,.83,2.26h-2.53c-.16-.58-.37-1.02-.62-1.31-.45-.53-1.12-.79-2-.79s-1.61,.37-2.13,1.11c-.52,.74-.78,1.79-.78,3.15s.27,2.37,.82,3.05c.55,.68,1.25,1.01,2.09,1.01s1.53-.29,1.98-.87c.25-.31,.46-.78,.63-1.4h2.51c-.22,1.32-.77,2.39-1.66,3.22s-2.03,1.24-3.42,1.24c-1.72,0-3.07-.56-4.06-1.67-.98-1.12-1.48-2.66-1.48-4.61,0-2.11,.56-3.74,1.68-4.88Z"\n    /><path d="M134,14.45h-2.51V2.35h2.51V14.45Z" /><path\n      d="M141.14,5.3s.1,0,.2,.01v2.4c-.15-.02-.28-.03-.39-.03s-.21,0-.28,0c-.94,0-1.57,.31-1.89,.92-.18,.34-.27,.88-.27,1.59v4.27h-2.35V5.5h2.23v1.56c.36-.6,.67-1,.94-1.22,.44-.37,1.01-.55,1.71-.55,.04,0,.08,0,.11,0Z"\n    /><path d="M148.22,5.5h2.51l-3.23,8.94h-2.46l-3.21-8.94h2.62l1.86,6.6,1.9-6.6Z" /><path\n      d="M154.46,4.44h-2.37V2.28h2.37v2.16Zm-2.37,1.07h2.37V14.45h-2.37V5.5Z"\n    /><path\n      d="M163.93,6.02c.59,.48,.88,1.29,.88,2.41v6.02h-2.4v-5.44c0-.47-.06-.83-.19-1.08-.23-.46-.66-.69-1.3-.69-.79,0-1.33,.34-1.62,1.01-.15,.36-.23,.81-.23,1.36v4.84h-2.34V5.52h2.26v1.3c.3-.46,.58-.79,.85-.99,.48-.36,1.09-.54,1.82-.54,.92,0,1.67,.24,2.26,.73Z"\n    /><path\n      d="M172.81,5.69c.62,.28,1.14,.72,1.54,1.32,.37,.53,.6,1.15,.71,1.85,.06,.41,.09,1,.08,1.77h-6.51c.04,.9,.35,1.53,.93,1.89,.36,.22,.79,.34,1.29,.34,.53,0,.96-.14,1.3-.41,.18-.15,.34-.35,.48-.62h2.39c-.06,.53-.35,1.07-.87,1.62-.8,.87-1.92,1.3-3.36,1.3-1.19,0-2.24-.37-3.15-1.1-.91-.73-1.36-1.93-1.36-3.58,0-1.55,.41-2.74,1.23-3.56s1.89-1.24,3.2-1.24c.78,0,1.48,.14,2.1,.42Zm-3.5,2.02c-.33,.34-.54,.8-.62,1.38h4.03c-.04-.62-.25-1.09-.62-1.41s-.83-.48-1.39-.48c-.6,0-1.07,.17-1.4,.51Z"\n    /><path\n      d="M102.72,22.56h2.34l3.46,10.19,3.44-10.19h2.31v12.05h-1.55v-7.11c0-.25,0-.65,.02-1.22,.01-.57,.02-1.18,.02-1.83l-3.44,10.16h-1.62l-3.46-10.16v.37c0,.3,0,.75,.02,1.35,.01,.6,.02,1.05,.02,1.33v7.11h-1.56v-12.05Z"\n    /><path\n      d="M121.27,29.28c.34-.04,.57-.19,.68-.43,.07-.13,.1-.32,.1-.57,0-.5-.18-.87-.54-1.1-.36-.23-.87-.34-1.54-.34-.77,0-1.32,.21-1.64,.62-.18,.23-.3,.57-.35,1.03h-1.38c.03-1.08,.38-1.84,1.05-2.26,.68-.42,1.46-.64,2.35-.64,1.03,0,1.87,.2,2.52,.59,.64,.39,.96,1.01,.96,1.84v5.06c0,.15,.03,.28,.09,.37,.06,.09,.2,.14,.4,.14,.07,0,.14,0,.22-.01,.08,0,.17-.02,.26-.04v1.09c-.23,.07-.4,.11-.53,.12-.12,.02-.28,.02-.49,.02-.51,0-.88-.18-1.11-.54-.12-.19-.21-.46-.25-.81-.3,.39-.73,.74-1.3,1.03-.56,.29-1.18,.43-1.86,.43-.82,0-1.48-.25-2-.74-.52-.5-.77-1.11-.77-1.86,0-.81,.25-1.45,.76-1.9,.51-.45,1.18-.72,2-.83l2.35-.3Zm-3.11,3.99c.31,.25,.68,.37,1.11,.37,.52,0,1.02-.12,1.51-.36,.82-.4,1.23-1.05,1.23-1.96v-1.19c-.18,.11-.41,.21-.7,.29-.28,.08-.56,.13-.84,.16l-.89,.11c-.54,.07-.94,.18-1.21,.34-.45,.26-.68,.67-.68,1.23,0,.43,.16,.76,.47,1.01Z"\n    /><path\n      d="M131.71,26.29c.62,.48,.99,1.31,1.12,2.49h-1.44c-.09-.54-.29-.99-.6-1.35-.31-.36-.81-.54-1.5-.54-.94,0-1.61,.46-2.02,1.38-.26,.6-.39,1.33-.39,2.21s.19,1.62,.56,2.22c.37,.6,.96,.9,1.75,.9,.61,0,1.1-.19,1.46-.56,.36-.37,.61-.89,.74-1.54h1.44c-.16,1.16-.57,2.02-1.23,2.56s-1.5,.81-2.52,.81c-1.15,0-2.06-.42-2.75-1.26s-1.03-1.89-1.03-3.15c0-1.54,.37-2.74,1.12-3.6,.75-.86,1.7-1.29,2.86-1.29,.99,0,1.79,.24,2.42,.72Z"\n    /><path\n      d="M134.3,22.51h1.48v4.5c.35-.44,.66-.75,.94-.94,.48-.31,1.07-.47,1.78-.47,1.27,0,2.14,.45,2.59,1.34,.25,.49,.37,1.16,.37,2.03v5.64h-1.52v-5.54c0-.65-.08-1.12-.25-1.42-.27-.48-.77-.72-1.51-.72-.61,0-1.17,.21-1.67,.63-.5,.42-.75,1.22-.75,2.39v4.66h-1.48v-12.09Z"\n    /><path d="M143.65,22.56h1.5v1.67h-1.5v-1.67Zm0,3.31h1.5v8.74h-1.5v-8.74Z" /><path\n      d="M147.38,25.82h1.4v1.25c.42-.51,.86-.88,1.32-1.11s.98-.34,1.55-.34c1.25,0,2.09,.43,2.53,1.3,.24,.48,.36,1.16,.36,2.04v5.64h-1.5v-5.54c0-.54-.08-.97-.24-1.3-.26-.55-.74-.82-1.43-.82-.35,0-.64,.04-.86,.11-.41,.12-.76,.36-1.07,.72-.25,.29-.41,.59-.48,.9-.07,.31-.11,.75-.11,1.32v4.6h-1.48v-8.79Z"\n    /><path\n      d="M162.19,26.06c.58,.29,1.03,.67,1.34,1.14,.29,.44,.49,.96,.59,1.55,.09,.4,.13,1.05,.13,1.94h-6.44c.03,.89,.24,1.61,.63,2.14,.39,.54,1,.81,1.83,.81,.77,0,1.39-.25,1.85-.76,.26-.3,.45-.64,.56-1.02h1.45c-.04,.32-.17,.68-.38,1.08-.22,.4-.46,.72-.73,.97-.45,.44-1,.73-1.67,.89-.36,.09-.76,.13-1.21,.13-1.09,0-2.02-.4-2.78-1.19-.76-.8-1.14-1.91-1.14-3.34s.38-2.56,1.15-3.44,1.77-1.32,3-1.32c.62,0,1.23,.15,1.81,.44Zm.54,3.45c-.06-.64-.2-1.15-.42-1.53-.41-.71-1.08-1.07-2.03-1.07-.68,0-1.25,.24-1.71,.73-.46,.49-.7,1.11-.73,1.87h4.88Z"\n    /><path d="M170.93,22.56h1.63v10.61h6.1v1.44h-7.74v-12.05Z" /><path\n      d="M185.55,26.06c.58,.29,1.03,.67,1.34,1.14,.29,.44,.49,.96,.59,1.55,.09,.4,.13,1.05,.13,1.94h-6.44c.03,.89,.24,1.61,.63,2.14,.39,.54,1,.81,1.83,.81,.77,0,1.39-.25,1.85-.76,.26-.3,.45-.64,.56-1.02h1.45c-.04,.32-.17,.68-.38,1.08-.22,.4-.46,.72-.73,.97-.45,.44-1,.73-1.67,.89-.36,.09-.76,.13-1.21,.13-1.09,0-2.02-.4-2.78-1.19-.76-.8-1.14-1.91-1.14-3.34s.38-2.56,1.15-3.44,1.77-1.32,3-1.32c.62,0,1.23,.15,1.81,.44Zm.54,3.45c-.06-.64-.2-1.15-.42-1.53-.41-.71-1.08-1.07-2.03-1.07-.68,0-1.25,.24-1.71,.73-.46,.49-.7,1.11-.73,1.87h4.88Z"\n    /><path\n      d="M194.13,29.28c.34-.04,.57-.19,.68-.43,.07-.13,.1-.32,.1-.57,0-.5-.18-.87-.54-1.1-.36-.23-.87-.34-1.54-.34-.77,0-1.32,.21-1.64,.62-.18,.23-.3,.57-.35,1.03h-1.38c.03-1.08,.38-1.84,1.05-2.26,.68-.42,1.46-.64,2.35-.64,1.03,0,1.87,.2,2.52,.59,.64,.39,.96,1.01,.96,1.84v5.06c0,.15,.03,.28,.09,.37,.06,.09,.2,.14,.4,.14,.07,0,.14,0,.22-.01,.08,0,.17-.02,.26-.04v1.09c-.23,.07-.4,.11-.53,.12-.12,.02-.28,.02-.49,.02-.51,0-.88-.18-1.11-.54-.12-.19-.21-.46-.25-.81-.3,.39-.73,.74-1.3,1.03s-1.18,.43-1.86,.43c-.81,0-1.48-.25-2-.74-.52-.5-.78-1.11-.78-1.86,0-.81,.25-1.45,.76-1.9,.51-.45,1.18-.72,2-.83l2.35-.3Zm-3.11,3.99c.31,.25,.68,.37,1.11,.37,.52,0,1.02-.12,1.51-.36,.82-.4,1.23-1.05,1.23-1.96v-1.19c-.18,.11-.41,.21-.7,.29-.28,.08-.56,.13-.84,.16l-.89,.11c-.54,.07-.94,.18-1.21,.34-.45,.26-.68,.67-.68,1.23,0,.43,.16,.76,.47,1.01Z"\n    /><path\n      d="M198.8,25.82h1.4v1.52c.12-.3,.4-.65,.84-1.08,.45-.42,.97-.64,1.55-.64,.03,0,.07,0,.14,0s.18,.02,.34,.03v1.56c-.09-.02-.17-.03-.24-.03-.07,0-.15,0-.24,0-.74,0-1.32,.24-1.71,.72s-.6,1.03-.6,1.65v5.05h-1.48v-8.79Z"\n    /><path\n      d="M204.36,25.82h1.4v1.25c.42-.51,.86-.88,1.32-1.11s.98-.34,1.55-.34c1.25,0,2.09,.43,2.53,1.3,.24,.48,.36,1.16,.36,2.04v5.64h-1.5v-5.54c0-.54-.08-.97-.24-1.3-.26-.55-.74-.82-1.43-.82-.35,0-.64,.04-.86,.11-.41,.12-.76,.36-1.07,.72-.25,.29-.41,.59-.48,.9-.07,.31-.11,.75-.11,1.32v4.6h-1.48v-8.79Z"\n    /><path d="M213.7,22.56h1.5v1.67h-1.5v-1.67Zm0,3.31h1.5v8.74h-1.5v-8.74Z" /><path\n      d="M217.43,25.82h1.4v1.25c.42-.51,.86-.88,1.32-1.11s.98-.34,1.55-.34c1.25,0,2.09,.43,2.53,1.3,.24,.48,.36,1.16,.36,2.04v5.64h-1.5v-5.54c0-.54-.08-.97-.24-1.3-.26-.55-.74-.82-1.43-.82-.35,0-.64,.04-.86,.11-.41,.12-.76,.36-1.07,.72-.25,.29-.41,.59-.48,.9-.07,.31-.11,.75-.11,1.32v4.6h-1.48v-8.79Z"\n    /><path\n      d="M231.68,26.17c.28,.19,.56,.47,.85,.84v-1.11h1.36v7.99c0,1.12-.16,2-.49,2.64-.61,1.19-1.77,1.79-3.47,1.79-.95,0-1.74-.21-2.39-.64-.64-.42-1.01-1.09-1.08-1.99h1.5c.07,.39,.21,.7,.43,.91,.33,.33,.86,.49,1.57,.49,1.13,0,1.87-.4,2.22-1.2,.21-.47,.3-1.31,.29-2.52-.3,.45-.65,.78-1.07,1-.42,.22-.97,.33-1.65,.33-.95,0-1.78-.34-2.5-1.01-.71-.68-1.07-1.79-1.07-3.35,0-1.47,.36-2.62,1.08-3.45s1.59-1.24,2.6-1.24c.69,0,1.29,.17,1.8,.51Zm.18,1.58c-.45-.52-1.02-.79-1.71-.79-1.04,0-1.75,.49-2.13,1.46-.2,.52-.3,1.2-.3,2.04,0,.99,.2,1.74,.6,2.26,.4,.52,.94,.77,1.62,.77,1.06,0,1.81-.48,2.24-1.44,.24-.54,.36-1.17,.36-1.89,0-1.09-.22-1.9-.67-2.42Z"\n    /><path\n      d="M102.96,42.71h5.58c.92,0,1.68,.13,2.27,.4,1.13,.51,1.7,1.46,1.7,2.85,0,.72-.15,1.31-.45,1.77-.3,.46-.72,.83-1.25,1.11,.47,.19,.82,.44,1.06,.75s.37,.82,.4,1.52l.06,1.62c.02,.46,.05,.8,.11,1.03,.1,.38,.27,.63,.52,.74v.27h-2c-.05-.1-.1-.24-.13-.4s-.06-.48-.08-.95l-.1-2.01c-.04-.79-.33-1.32-.88-1.58-.31-.15-.8-.22-1.47-.22h-3.72v5.17h-1.63v-12.05Zm5.41,5.52c.77,0,1.37-.15,1.82-.46,.45-.31,.67-.86,.67-1.66,0-.86-.31-1.44-.94-1.75-.33-.16-.78-.25-1.34-.25h-3.99v4.12h3.77Z"\n    /><path\n      d="M120.17,46.22c.59,.29,1.03,.67,1.34,1.14,.29,.44,.49,.96,.59,1.55,.09,.41,.13,1.05,.13,1.94h-6.44c.03,.89,.24,1.61,.63,2.14,.39,.54,1,.81,1.83,.81,.77,0,1.39-.25,1.85-.76,.26-.3,.45-.64,.56-1.03h1.45c-.04,.32-.17,.68-.38,1.08-.22,.4-.46,.72-.73,.97-.45,.44-1,.73-1.67,.89-.36,.09-.76,.13-1.21,.13-1.09,0-2.02-.4-2.78-1.19-.76-.8-1.14-1.91-1.14-3.34s.38-2.56,1.15-3.44c.77-.88,1.77-1.32,3-1.32,.62,0,1.23,.15,1.81,.44Zm.54,3.45c-.06-.64-.2-1.15-.42-1.53-.4-.71-1.08-1.07-2.03-1.07-.68,0-1.25,.24-1.71,.73-.46,.49-.7,1.11-.73,1.87h4.88Z"\n    /><path\n      d="M123.93,46.02h1.44v1.16c.3-.4,.62-.71,.97-.93,.5-.33,1.08-.49,1.76-.49,1,0,1.84,.38,2.54,1.14,.69,.76,1.04,1.85,1.04,3.27,0,1.91-.5,3.28-1.5,4.1-.63,.52-1.37,.78-2.21,.78-.66,0-1.22-.14-1.67-.43-.26-.16-.55-.45-.88-.84v4.49h-1.48v-12.25Zm5.54,6.89c.46-.58,.69-1.44,.69-2.59,0-.7-.1-1.3-.3-1.8-.38-.97-1.08-1.45-2.1-1.45s-1.72,.51-2.1,1.53c-.2,.55-.3,1.24-.3,2.08,0,.68,.1,1.25,.3,1.73,.38,.91,1.08,1.36,2.1,1.36,.69,0,1.26-.29,1.72-.87Z"\n    /><path\n      d="M139.8,46.86c.78,.75,1.17,1.87,1.17,3.33s-.34,2.59-1.03,3.51c-.69,.92-1.76,1.39-3.21,1.39-1.21,0-2.17-.41-2.88-1.23s-1.07-1.92-1.07-3.29c0-1.48,.37-2.65,1.12-3.53,.75-.88,1.76-1.31,3.02-1.31,1.13,0,2.09,.38,2.87,1.13Zm-.92,5.84c.36-.74,.55-1.57,.55-2.47,0-.82-.13-1.49-.39-2-.42-.81-1.13-1.21-2.15-1.21-.9,0-1.56,.34-1.97,1.03-.41,.69-.62,1.52-.62,2.49s.21,1.71,.62,2.34,1.06,.94,1.95,.94c.98,0,1.65-.37,2.01-1.11Z"\n    /><path\n      d="M143.61,52.01c.04,.49,.17,.87,.37,1.13,.37,.48,1.02,.71,1.94,.71,.55,0,1.03-.12,1.44-.36,.42-.24,.62-.61,.62-1.1,0-.38-.17-.66-.5-.86-.21-.12-.63-.26-1.26-.42l-1.17-.29c-.75-.19-1.3-.39-1.66-.62-.63-.4-.95-.95-.95-1.66,0-.83,.3-1.5,.9-2.02s1.4-.77,2.42-.77c1.32,0,2.28,.39,2.86,1.17,.37,.49,.54,1.02,.53,1.59h-1.39c-.03-.33-.15-.64-.35-.91-.34-.39-.93-.58-1.76-.58-.56,0-.98,.11-1.27,.32-.29,.21-.43,.49-.43,.84,0,.38,.19,.69,.57,.92,.22,.14,.54,.26,.97,.36l.98,.24c1.06,.26,1.77,.51,2.13,.75,.57,.38,.86,.97,.86,1.78s-.3,1.46-.89,2.03c-.59,.57-1.5,.85-2.71,.85-1.31,0-2.23-.3-2.78-.89s-.83-1.33-.87-2.2h1.42Z"\n    /><path d="M151.13,42.71h1.5v1.67h-1.5v-1.67Zm0,3.31h1.5v8.74h-1.5v-8.74Z" /><path\n      d="M155.16,43.53h1.49v2.45h1.4v1.21h-1.4v5.73c0,.31,.1,.51,.31,.62,.12,.06,.31,.09,.57,.09,.07,0,.15,0,.23,0s.18,0,.29-.02v1.17c-.17,.05-.35,.08-.53,.11-.18,.02-.38,.03-.59,.03-.69,0-1.16-.18-1.4-.53s-.37-.81-.37-1.37v-5.82h-1.19v-1.21h1.19v-2.45Z"\n    /><path\n      d="M165.94,46.86c.78,.75,1.17,1.87,1.17,3.33s-.34,2.59-1.03,3.51c-.69,.92-1.76,1.39-3.21,1.39-1.21,0-2.17-.41-2.88-1.23s-1.07-1.92-1.07-3.29c0-1.48,.37-2.65,1.12-3.53,.75-.88,1.76-1.31,3.02-1.31,1.13,0,2.09,.38,2.87,1.13Zm-.92,5.84c.36-.74,.55-1.57,.55-2.47,0-.82-.13-1.49-.39-2-.42-.81-1.13-1.21-2.15-1.21-.9,0-1.56,.34-1.97,1.03-.41,.69-.62,1.52-.62,2.49s.21,1.71,.62,2.34,1.06,.94,1.95,.94c.98,0,1.65-.37,2.01-1.11Z"\n    /><path\n      d="M168.91,45.98h1.4v1.52c.12-.3,.4-.66,.84-1.08,.45-.42,.97-.64,1.55-.64,.03,0,.07,0,.14,0,.07,0,.18,.02,.34,.03v1.56c-.09-.02-.17-.03-.24-.03-.07,0-.15,0-.24,0-.74,0-1.32,.24-1.71,.72s-.6,1.03-.6,1.65v5.05h-1.48v-8.79Z"\n    /><path\n      d="M179.95,45.98h1.63c-.21,.56-.67,1.85-1.39,3.86-.54,1.51-.98,2.74-1.34,3.69-.85,2.24-1.46,3.61-1.8,4.1-.35,.49-.95,.74-1.8,.74-.21,0-.37,0-.48-.03-.11-.02-.25-.05-.41-.09v-1.35c.26,.07,.44,.12,.56,.13,.12,.02,.22,.02,.3,.02,.27,0,.47-.04,.6-.14,.13-.09,.24-.2,.32-.33,.03-.04,.13-.27,.3-.67,.17-.4,.29-.71,.37-.9l-3.25-9.04h1.67l2.35,7.15,2.37-7.15Z"\n    /></g\n  ><g\n    ><path\n      d="M23.64,7.16c.69,.18,1.37,.39,1.8,1,.27,.38,.5,.8,.73,1.21,.46,.82,.91,1.65,1.37,2.47,.13,.23,.33,.29,.6,.27,5.99-.44,11.87,.28,17.67,1.77,4.55,1.17,8.9,2.89,13.27,4.57,8.7,3.34,17.28,6.96,25.74,10.86,4.19,1.93,8.32,4,12.48,6.01,.19,.09,.36,.22,.55,.3,1.31,.55,1.76,1.67,1.89,2.95,.23,2.31-.28,4.52-1.09,6.66-.17,.44-.61,.83-1.01,1.11-1.71,1.19-3.66,1.8-5.67,2.22-2.3,.48-4.53,.15-6.77-.41-3.87-.96-7.74-1.91-11.64-2.76-5.01-1.1-10.07-1.84-15.21-1.89-4-.04-7.96,.33-11.73,1.77-1.85,.71-3.63,1.59-5.44,2.39-3.13,1.38-6.29,2.71-9.55,3.77-4.1,1.34-8.28,1.87-12.58,1.48-2.25-.21-4.5-.37-6.74-.66-2.16-.28-4.29-.78-6.28-1.72-1.74-.82-3.3-1.9-4.12-3.67-.59-1.29-.97-2.68-1.35-4.05-.24-.87-.32-1.78-.47-2.67,0-.08-.06-.16-.09-.23v-.47c.03-.09,.07-.19,.08-.28v-1.72c0-.09-.05-.19-.08-.28v-.47c.03-.06,.09-.12,.09-.19,.37-3.26,1.23-6.41,2.48-9.44,1.04-2.54,2.52-4.8,4.55-6.68,.05-.05,.09-.11,.11-.14-.41-.39-.83-.73-1.18-1.13-1.04-1.16-1.06-2.58-.08-3.79,.64-.79,1.43-1.4,2.36-1.8,1.33-.58,2.6-.47,3.73,.46,.5,.41,.93,.92,1.34,1.43,.2,.25,.36,.29,.65,.18,1.27-.5,2.54-1.01,3.83-1.43,.61-.2,.94-.54,1.03-1.13,.13-.87,.24-1.74,.3-2.61,.11-1.69,.86-2.62,2.51-3.04,.25-.06,.49-.14,.73-.21h1.19Zm.49,1.39s-.05-.02-.08-.03c0,.03,.01,.06,.02,.09,.07,.18,.14,.37,.22,.55,1.87,4.08,3.73,8.15,5.6,12.22,.29,.64,.59,1.28,.89,1.92,.16-.04,.28-.09,.41-.1,.23-.02,.3-.12,.32-.35,.2-2.17,.41-4.33,.61-6.5,0-.12-.09-.29-.19-.36-.68-.48-.77-1.34-.14-1.87,.35-.29,.04-.55,0-.81,0-.08-.25-.19-.38-.19-1.18,.03-2.36,.07-3.54,.14-.34,.02-.64-.04-.84-.31-.44-.59-.89-1.17-1.26-1.79-.33-.55-.52-1.18-.85-1.73-.2-.33-.53-.59-.79-.88ZM15.87,29.06c-.36-.11-.63-.21-.9-.28-.13-.03-.31-.05-.41,.01-2.08,1.26-4.15,2.53-6.22,3.79-.18,.11-.23,.21-.18,.44,.23,1.02-.37,1.98-1.37,2.16-.31,.06-.37,.2-.4,.46-.19,1.4-.4,2.8-.59,4.21-.19,1.36-.37,2.73-.55,4.04,.33,.24,.67,.41,.91,.67s.38,.61,.58,.95c3.5-.21,7.04-.42,10.59-.63,.14-.96,.67-1.57,1.6-1.83-1.03-4.7-2.04-9.37-3.05-13.98h-.01Zm4.25,13.95c.36,.38,.69,.67,.95,1.02,.15,.21,.28,.25,.51,.2,3.75-.85,7.5-1.69,11.25-2.53,.2-.05,.3-.12,.31-.36,.03-.71,.34-1.3,.96-1.67,.29-.17,.33-.32,.25-.62-1.04-4.14-2.09-8.28-3.1-12.43-.14-.57-.35-1.01-.94-1.23-1.57,1.65-3.15,3.32-4.73,4.99,.66,.83,.82,1.71,.29,2.62-.57,.97-1.47,1.24-2.57,1.02-1.07,3.04-2.14,6.07-3.17,9h-.01Zm27.74-.27c.05-.57,.24-1.05,.72-1.31,.3-.16,.32-.32,.24-.62l-4.5-16.74c-.04-.16,0-.45-.31-.4-.29,.05-.64-.19-.85,.3-2.23,5.12-4.48,10.23-6.74,15.34-.09,.22-.09,.34,.11,.49,.41,.3,.67,.72,.73,1.22,.04,.34,.19,.42,.49,.45,2.63,.32,5.26,.66,7.89,.99,.73,.09,1.45,.18,2.21,.28h0Zm-2.68-19.52c-.39,.11-.47,.3-.36,.68,.43,1.49,.81,2.98,1.21,4.48,1.1,4.13,2.21,8.25,3.31,12.38,.07,.24,.15,.38,.43,.46,.31,.08,.61,.29,.86,.5,.16,.13,.25,.2,.46,.11,2.25-.98,4.5-1.95,6.75-2.92,.28-.12,.47-.24,.41-.59-.03-.14,.02-.33,.1-.45,.17-.27,.08-.43-.12-.64-3.82-4.08-7.63-8.17-11.44-12.26-.54-.58-1.09-1.17-1.62-1.74h0Zm-13.57,2.62c0,.09,0,.13,.01,.16,1.09,4.33,2.18,8.67,3.25,13.01,.12,.49,.48,.22,.72,.32,.26,.11,.3-.12,.37-.28,2.17-4.94,4.34-9.89,6.52-14.83,.11-.26,.22-.52,.31-.72-.29-.32-.57-.57-.77-.87-.14-.21-.26-.26-.51-.21-1.88,.41-3.77,.81-5.66,1.21-1.02,.22-2.04,.44-3.07,.66,0,.84-.39,1.35-1.18,1.55h0Zm52.47,4.3c-.07,.1-.09,.13-.11,.16-1.6,3.72-3.2,7.44-4.8,11.16-.04,.09-.03,.23,.02,.31,.09,.17,.23,.31,.35,.48,.07-.02,.13-.03,.19-.05,2.9-1.15,5.8-2.3,8.7-3.46,.11-.05,.22-.23,.23-.36,.05-.58,.29-1.03,.83-1.29,.52-.25,1.03-.2,1.48,.16,.19,.15,.31,.1,.48,0,.98-.61,1.96-1.21,2.95-1.82,.09-.06,.17-.13,.33-.25-3.6-1.7-7.12-3.37-10.66-5.04h0Zm-62.03,.49c.39-.28,.7-.56,1.07-.74,.27-.13,.33-.26,.32-.53-.03-1.43-.05-2.86-.07-4.29-.07-4.85-.14-9.71-.21-14.56v-1.07s-.08,0-.11-.01c-.05,.11-.1,.23-.15,.34-.57,1.49-1.15,2.99-1.72,4.48-1.52,3.96-3.05,7.93-4.58,11.89-.11,.27-.16,.48,.08,.73,.16,.17,.18,.48,.27,.72,.04,.11,.09,.25,.18,.3,1.65,.93,3.3,1.84,4.92,2.74Zm54.36-3.87c-.51-.21-.97-.42-1.45-.61-.1-.04-.26-.01-.37,.03-3.4,1.35-6.8,2.7-10.2,4.05-.21,.08-.24,.19-.27,.4-.05,.37-.13,.76-.29,1.08-.14,.27-.11,.42,.06,.65,1.35,1.83,2.68,3.66,4.01,5.5,.19,.27,.35,.52,.74,.3,.12-.07,.32-.06,.46,0,.3,.1,.41-.07,.55-.29,2.03-3.32,4.06-6.65,6.09-9.97,.22-.37,.44-.74,.68-1.13h-.01ZM23.73,9.24s-.04,.01-.06,.02c.11,6.81,.21,13.62,.32,20.42,.29,.07,.57,.09,.78,.21,.32,.18,.48,.05,.69-.17,1.4-1.49,2.81-2.98,4.23-4.46,.25-.26,.48-.5,.42-.91-.02-.13,.04-.3,.11-.41,.15-.22,.09-.4,0-.62-2.11-4.59-4.21-9.17-6.32-13.76-.05-.11-.11-.22-.17-.33h0ZM91.73,47.46c.53-.13,1.02-.24,1.51-.37,1.33-.38,2.61-.88,3.76-1.66,.37-.25,.63-.56,.77-1,.42-1.33,.74-2.68,.86-4.07,.07-.86,.06-1.73-.23-2.57-.13-.37-.29-.73-.68-.93-.73-.38-1.46-.78-2.18-1.18-.2-.11-.35-.09-.54,.03-1.1,.69-2.21,1.37-3.32,2.04-.17,.1-.22,.2-.18,.41,.12,.61-.1,1.13-.63,1.45-.25,.15-.29,.3-.25,.57,.24,1.54,.46,3.08,.69,4.62,.13,.87,.26,1.73,.4,2.66h.02Zm-1.66-7.47c-.39-.22-.73-.35-.98-.58-.19-.16-.31-.17-.51-.09-.63,.26-1.27,.51-1.9,.76-2.22,.88-4.44,1.76-6.66,2.63-.23,.09-.35,.18-.34,.47,.02,.52-.19,.97-.56,1.34-.33,.33-.17,.93,.29,1.04,2.5,.61,4.99,1.22,7.49,1.82,1.4,.34,2.82,.41,4.29,.15-.38-2.55-.76-5.09-1.12-7.54Zm-56.4,2.77c-.35-.2-.26-.64-.73-.53-3.77,.87-7.55,1.71-11.32,2.55-.23,.05-.28,.16-.3,.37-.05,.79-.47,1.34-1.16,1.7-.08,.04-.15,.08-.24,.13,.27,1.64,.53,3.27,.8,4.94,1.27-.04,2.49-.07,3.7-.14,.16,0,.33-.14,.45-.27,2.25-2.26,4.48-4.54,6.73-6.8,.65-.65,1.33-1.26,2.07-1.96h0ZM12.08,22.73c.09,.12,.18,.24,.27,.35,.85,1.03,1.7,2.07,2.54,3.1,.35,.42,1.01,.32,1.2-.19,1.96-5.08,3.92-10.17,5.87-15.25,.3-.78,.59-1.56,.92-2.43-.45,.1-.83,.17-1.2,.27-.76,.21-1.2,.72-1.28,1.51-.05,.47-.08,.94-.1,1.41-.06,1.06-.21,2.09-.8,3-.11,.18-.29,.36-.48,.44-1.65,.63-3.31,1.25-4.98,1.84-.3,.11-.65,.11-1.05,.18-.34,.97-.72,2.04-1.08,3.12-.03,.08,.07,.22,.13,.31,.17,.28,.41,.52,.5,.82,.19,.58-.07,1.07-.48,1.51h.02Zm66.56,18.66c1.51-3.53,3.02-7.02,4.52-10.51-.03-.02-.05-.04-.08-.06-4.26,2.73-8.52,5.46-12.77,8.19,.03,.22,.03,.42,.09,.6,.03,.11,.13,.26,

In [74]:
# Converting raw html string to html tree parser using beautifulSoup

soup = BeautifulSoup(response.text, "html.parser")

In [75]:
soup

<!DOCTYPE html>

<html data-theme="light" lang="en">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta content="Discover datasets around the world!" name="description"/>
<link href="/favicon.ico" rel="icon"/>
<link href="/apple-touch-icon.png" rel="apple-touch-icon"/>
<!-- Provides metadata used when the app is installed on a mobile device or desktop. -->
<!-- See https://developers.google.com/web/fundamentals/web-app-manifest/ -->
<link href="/manifest.json" rel="manifest"/>
<title>UCI Machine Learning Repository</title>
<link href="../../_app/immutable/assets/0.ab4ca364.css" rel="stylesheet"/>
<link href="../../_app/immutable/assets/Autocomplete.3d8e18c6.css" rel="stylesheet"/>
<link href="../../_app/immutable/assets/DropdownText.035f3ed6.css" rel="stylesheet"/>
<link href="../../_app/immutable/assets/JsonDiff.b38ce334.css" rel="stylesheet"/>
<link href="../../_app/immutable/assets/Variables.ad52176b.css" rel="stylesheet"/><title>Online Retail - UCI Machine Learning Repository</title><!-- HEAD_svelte-mjc4kk_START --><script async="" src="https://www.googletagmanager.com/gtag/js?id=G-MTKKEPF231"></script><!-- HTML_TAG_START -->
<script>
      window.dataLayer = window.dataLayer ?? []
      function gtag() {
        dataLayer.push(arguments)
      }
      gtag('js', new Date())
      gtag('config', "G-MTKKEPF231")
    </script>
<!-- HTML_TAG_END --><!-- HEAD_svelte-mjc4kk_END --><!-- HEAD_svelte-q2bizo_START --><!-- HEAD_svelte-q2bizo_END -->
</head>
<body>

In [76]:
metadata = {}

In [77]:
soup.find("table")

<table class="table my-4 w-full"> <thead><tr><th>Variable Name</th><th>Role</th><th>Type</th><th>Description</th><th>Units</th><th>Missing Values</th></tr></thead> <tbody><tr><td>InvoiceNo</td><td>ID</td><td>Categorical</td><td>a 6-digit integral number uniquely assigned to each transaction. If this code starts with letter 'c', it indicates a cancellation</td><td></td><td>no</td> </tr><tr><td>StockCode</td><td>ID</td><td>Categorical</td><td>a 5-digit integral number uniquely assigned to each distinct product</td><td></td><td>no</td> </tr><tr><td>Description</td><td>Feature</td><td>Categorical</td><td>product name</td><td></td><td>no</td> </tr><tr><td>Quantity</td><td>Feature</td><td>Integer</td><td>the quantities of each product (item) per transaction</td><td></td><td>no</td> </tr><tr><td>InvoiceDate</td><td>Feature</td><td>Date</td><td>the day and time when each transaction was generated</td><td></td><td>no</td> </tr><tr><td>UnitPrice</td><td>Feature</td><td>Continuous</td><td>product price per unit</td><td>sterling</td><td>no</td> </tr><tr><td>CustomerID</td><td>Feature</td><td>Categorical</td><td>a 5-digit integral number uniquely assigned to each customer</td><td></td><td>no</td> </tr><tr><td>Country</td><td>Feature</td><td>Categorical</td><td>the name of the country where each customer resides</td><td></td><td>no</td> </tr></tbody></table>

In [88]:
table = soup.find("table")
header_keys = []
values = []

if table:
    for row in table.find_all("tr"):
        cols = row.find_all("th")

        if len(cols) == 6:
            for i in range(len(cols)):
                key = cols[i].get_text(strip=True)
                header_keys.append(key)

    
    for row in table.find_all("tr"):
        cols = row.find_all("td")

        if len(cols) == 6:
            data = []
            for i in range(len(cols)):
                value = cols[i].get_text(strip=True)
                data.append(value)
            values.append(data)

# print(header_keys)
# print(values)
# print(dict(zip([1,2,3], [45,56,67])))


table_data = {(zip(header_keys,row_data)) for row_data in values }

In [89]:
table_data

{<zip at 0x21b2580b240>,
 <zip at 0x21b2580b340>,
 <zip at 0x21b2580b380>,
 <zip at 0x21b2580b3c0>,
 <zip at 0x21b2580b400>,
 <zip at 0x21b2580b440>,
 <zip at 0x21b2580b480>,
 <zip at 0x21b2580b500>}

In [90]:
for i in table_data:
    print(dict(i))

{'Variable Name': 'Quantity', 'Role': 'Feature', 'Type': 'Integer', 'Description': 'the quantities of each product (item) per transaction', 'Units': '', 'Missing Values': 'no'}
{'Variable Name': 'InvoiceNo', 'Role': 'ID', 'Type': 'Categorical', 'Description': "a 6-digit integral number uniquely assigned to each transaction. If this code starts with letter 'c', it indicates a cancellation", 'Units': '', 'Missing Values': 'no'}
{'Variable Name': 'CustomerID', 'Role': 'Feature', 'Type': 'Categorical', 'Description': 'a 5-digit integral number uniquely assigned to each customer', 'Units': '', 'Missing Values': 'no'}
{'Variable Name': 'UnitPrice', 'Role': 'Feature', 'Type': 'Continuous', 'Description': 'product price per unit', 'Units': 'sterling', 'Missing Values': 'no'}
{'Variable Name': 'Country', 'Role': 'Feature', 'Type': 'Categorical', 'Description': 'the name of the country where each customer resides', 'Units': '', 'Missing Values': 'no'}
{'Variable Name': 'Description', 'Role': 'Feature', 'Type': 'Categorical', 'Description': 'product name', 'Units': '', 'Missing Values': 'no'}
{'Variable Name': 'StockCode', 'Role': 'ID', 'Type': 'Categorical', 'Description': 'a 5-digit integral number uniquely assigned to each distinct product', 'Units': '', 'Missing Values': 'no'}
{'Variable Name': 'InvoiceDate', 'Role': 'Feature', 'Type': 'Date', 'Description': 'the day and time when each transaction was generated', 'Units': '', 'Missing Values': 'no'}

In [96]:
# find the dataset info block

info_section = soup.find("div", {"class" : "relative flex flex-col gap-4 bg-base-100 p-4 shadow"})

In [97]:
info_section

<div class="relative flex flex-col gap-4 bg-base-100 p-4 shadow"> <div> <div> <p class="svelte-1xc1tf7" style="--clamp: 2; --display: -webkit-box"> <span>This is a transactional data set which contains all the transactions occurring between 01/12/2010 and 09/12/2011 for a UK-based and registered non-store online retail.</span></p> </div></div> <div class="grid grid-cols-8 gap-4 md:grid-cols-12"><div class="col-span-4"><h1 class="text-lg font-semibold text-primary" data-svelte-h="svelte-1mfm6at">Dataset Characteristics</h1> <p class="text-md">Multivariate, Sequential, Time-Series</p> </div><div class="col-span-4"><h1 class="text-lg font-semibold text-primary" data-svelte-h="svelte-1mfm6at">Subject Area</h1> <p class="text-md">Business</p> </div><div class="col-span-4"><h1 class="text-lg font-semibold text-primary" data-svelte-h="svelte-1mfm6at">Associated Tasks</h1> <p class="text-md">Classification, Clustering</p> </div><div class="col-span-4"><h1 class="text-lg font-semibold text-primary" data-svelte-h="svelte-1mfm6at">Feature Type</h1> <p class="text-md">Integer, Real</p> </div><div class="col-span-4"><h1 class="text-lg font-semibold text-primary" data-svelte-h="svelte-1mfm6at"># Instances</h1> <p class="text-md">541909</p> </div><div class="col-span-4"><h1 class="text-lg font-semibold text-primary" data-svelte-h="svelte-1mfm6at"># Features</h1> <p class="text-md">6</p> </div></div></div>

In [98]:
info_section.get_text()

'    This is a transactional data set which contains all the transactions occurring between 01/12/2010 and 09/12/2011 for a UK-based and registered non-store online retail.  Dataset Characteristics Multivariate, Sequential, Time-Series Subject Area Business Associated Tasks Classification, Clustering Feature Type Integer, Real # Instances 541909 # Features 6 '

In [99]:
info_section.get_text(" ", strip=True)

'This is a transactional data set which contains all the transactions occurring between 01/12/2010 and 09/12/2011 for a UK-based and registered non-store online retail. Dataset Characteristics Multivariate, Sequential, Time-Series Subject Area Business Associated Tasks Classification, Clustering Feature Type Integer, Real # Instances 541909 # Features 6'

In [ ]:
full_text = info_section.get_text(" ", strip=True)  # " " ensures paragraphs don't get smashed together
sentences = full_text.split(".")

In [101]:
sentences

['This is a transactional data set which contains all the transactions occurring between 01/12/2010 and 09/12/2011 for a UK-based and registered non-store online retail',
 ' Dataset Characteristics Multivariate, Sequential, Time-Series Subject Area Business Associated Tasks Classification, Clustering Feature Type Integer, Real # Instances 541909 # Features 6']

In [102]:
first_sentence = sentences[0] + "."
print(first_sentence)

This is a transactional data set which contains all the transactions occurring between 01/12/2010 and 09/12/2011 for a UK-based and registered non-store online retail.

In [ ]:
soup.find("div", {"class" : "col-span-4"})

In [105]:
soup.find_all("div", {"class" : "col-span-4"})

[<div class="col-span-4"><h1 class="text-lg font-semibold text-primary" data-svelte-h="svelte-1mfm6at">Dataset Characteristics</h1> <p class="text-md">Multivariate, Sequential, Time-Series</p> </div>,
 <div class="col-span-4"><h1 class="text-lg font-semibold text-primary" data-svelte-h="svelte-1mfm6at">Subject Area</h1> <p class="text-md">Business</p> </div>,
 <div class="col-span-4"><h1 class="text-lg font-semibold text-primary" data-svelte-h="svelte-1mfm6at">Associated Tasks</h1> <p class="text-md">Classification, Clustering</p> </div>,
 <div class="col-span-4"><h1 class="text-lg font-semibold text-primary" data-svelte-h="svelte-1mfm6at">Feature Type</h1> <p class="text-md">Integer, Real</p> </div>,
 <div class="col-span-4"><h1 class="text-lg font-semibold text-primary" data-svelte-h="svelte-1mfm6at"># Instances</h1> <p class="text-md">541909</p> </div>,
 <div class="col-span-4"><h1 class="text-lg font-semibold text-primary" data-svelte-h="svelte-1mfm6at"># Features</h1> <p class="text-md">6</p> </div>]

In [110]:
soup.find_all("div", {"class" : "col-span-4"})[0].h1.get_text(strip=True)

'Dataset Characteristics'

In [111]:
dataset_info = {}
for info in soup.find_all("div", {"class" : "col-span-4"}):
    key = info.h1.get_text(strip=True)
    value = info.p.get_text(strip=True)
    dataset_info[key] = value

In [112]:
dataset_info

{'Dataset Characteristics': 'Multivariate, Sequential, Time-Series',
 'Subject Area': 'Business',
 'Associated Tasks': 'Classification, Clustering',
 'Feature Type': 'Integer, Real',
 '# Instances': '541909',
 '# Features': '6'}